Calendar types
Ohtuprojekti-Fintraffic/lentovaraukset pull request #135
Opened 2023-02-19 05:57 UTC by hamidaebadi

Related to Issue #134 

## What changes has been added?
New calendar types added 
### Backend

### Frontend
Three types added into the file /shared/index.ts

- CalendarEvent: Define general type for a calendar Event
- ReservationCalendarEvent: Partial type of CalendarEvent. Used for reservations
- TimeslotsCalendarEvent: Created from CalendarEvent with a few omitted fields

## Expected Behaviour

2023-02-20 10:04 UTC, nualn approved these changes

2023-02-20 10:42 UTC, hamidaebadi commented
@nualn Mitä sitten tarkoittaa Varauksen kalenterityyppija vapaan aikaikkunan kalenterityyppi storyssä #76 ?

2023-02-20 11:07 UTC, nualn commented
En oo ihan varma. @Jokauppi pystyy varmaan avaamaan

2023-02-20 12:52 UTC, vaisest commented
```ts
import type { EventInput } from '@fullcalendar/core';

export type ReservationCalendarEvent = Pick<Required<EventInput>, 'id' | 'title' | 'start' | 'end'>;

export type TimeSlotsCalendarEvent = Pick<Required<EventInput>, 'id' | 'start' | 'end'>;
```

Tyyliin näin kai ehkä?

2023-02-20 13:08 UTC, hamidaebadi commented
@vaisest homma oli vähän epäselvä, mutta puhuin tästä Joonan kanssa discordis eilen. Kyseessä oli ehkä event-object, jonka palauttaa eventClick-funktiot. [Event-object](https://fullcalendar.io/docs/event-object).
Joka tapauksessa ei voida importata kalenterin valmiita tyyppejä sharediin. Tein kalenterin event-objektin uudelleen sisältäen oleellisimmat kentät. Tarvittaessa voidaan lisätä uusia kenttiä objektiin.

Ehkä ymmärsin homman väärin.

2023-02-20 13:12 UTC, vaisest commented
> @vaisest homma oli vähän epäselvä, mutta puhuin tästä Joonan kanssa discordis eilen. Kyseessä oli ehkä event-object, jonka palauttaa eventClick-funktiot. [Event-object](https://fullcalendar.io/docs/event-object). Joka tapauksessa ei voida importata kalenterin valmiita tyyppejä sharediin. Tein kalenterin event-objektin uudelleen sisältäen oleellisimmat kentät. Tarvittaessa voidaan lisätä uusia kenttiä objektiin.
> 
> Ehkä ymmärsin homman väärin.

Joo mutta siis eihän näitä tyyppejä tarvitse laittaa sharediin, kun niitä käytetään vain frontendissä. Saattaa olla helpompaa tehdä näin valitsemalla ne mitä käytetään. Esim nyt tuossa sun CalendarEventissä on id: number, mutta EventInputissa se on id: string

2023-02-20 13:19 UTC, vaisest requested changes
Asiasta keskusteltu kommenteissa. Vaikka tapaa ei vaihdettaisi muutama virhe on joka tapauksessa

2023-02-20 13:19 UTC, vaisest commented on frontend/src/pages/TimeSlotCalendar.tsx
> +
?

2023-02-20 13:19 UTC, vaisest commented on shared/src/index.ts
> +  id: number,
Tämä ainakin virheellinen. pitäisi olla string

2023-02-20 13:24 UTC, hamidaebadi commented on shared/src/index.ts
> +  id: number,
korjattu

2023-02-20 13:24 UTC, hamidaebadi commented on frontend/src/pages/TimeSlotCalendar.tsx
> +
korjattu

2023-02-20 13:28 UTC, hamidaebadi commented
@vaisest 
Voidaan nyt hyväksyä väliaikaisesti. Seuraavassa sprintissä sit korjataan. Veikkaan et ei ehditä nyt korjata

2023-02-20 13:40 UTC, vaisest commented
Kannattanee laittaa draftiksi sitten. Ei tätä tarvitse mergetä, kun ei ole käännösfunktioitakaan eikä tyyppejä lisätty mihinkään käyttöön. Lisäksi nuo pitää mielestäni siirtää tuolta sharedista kun ei backend näitä tyyppejä käytä.

2023-02-20 13:44 UTC, hamidaebadi commented
@vaisest Selvä juttu

2023-02-20 17:35 UTC, Jokauppi commented
> ```ts
> import type { EventInput } from '@fullcalendar/core';
> import type { ReservationEntry } from '@lentovaraukset/shared/src/index';
> 
> export type ReservationCalendarEvent = Pick<Required<EventInput>, 'id' | 'title' | 'start' | 'end'>;
> 
> export type TimeSlotsCalendarEvent = Pick<Required<EventInput>, 'id' | 'start' | 'end'>;
> 
> export function reservationEntryToCalendarEvent(re: ReservationEntry): ReservationCalendarEvent {
>   return {
>     id: re.id.toString(), title: re.aircraftId, start: re.start, end: re.end,
>   };
> }
> ```
> 
> Tyyliin näin kai ehkä jos ymmärsin oikein?

Tää näyttää mun mielestä ihan hyvältä toteutustavalta. Voin myös kattoo tätä myöhemmin tarkemmin kun tälle ei oo kumminkaan vielä kauheen akuuttia tarvetta.

2023-02-22 11:55 UTC, vaisest commented
Voisitko vielä lisätä nämä käyttöön frontendissä?

2023-02-23 11:27 UTC, hamidaebadi commented
> Voisitko vielä lisätä nämä käyttöön frontendissä?

@vaisest otin ne käyttöön. Tarkista vielä että ne on otettu käyttöön oikeissa paikoissa

2023-02-25 22:06 UTC, vaisest commented on frontend/src/queries/reservations.ts
> +const getReservations = async (from: Date, until: Date): Promise<ReservationEntry[]> => {
Tämä oli esim väärin

2023-02-25 22:07 UTC, vaisest commented
Korjasin tyyppejä jonkin verran. Anya oli vielä ja jotkut tyypit olivat väärin. Tämä koko homma on kyllä mennyt muutenkin niin hifistelyksi että tää pitäis nyt saada varmaan mergettyä pois alta

2023-03-16 08:25 UTC, closed without merging